#define lxb_html_interface_div(obj) ((lxb_html_div_element_t *) (obj))
#define lxb_css_syntax_token_comment(token) ((lxb_css_syntax_token_comment_t *) (token))
#define lexbor_str(p) {.data = (lxb_char_t *) (p), sizeof(p) - 1}
#define lexbor_max(val1,val2) ((val1) > (val2) ? (val1) : (val2))
#define lxb_dom_interface_processing_instruction(obj) ((lxb_dom_processing_instruction_t *) (obj))
#define lexbor_str_len(str) lexbor_str_get(str, length)
#define lxb_html_interface_frame_set(obj) ((lxb_html_frame_set_element_t *) (obj))
#define lxb_html_interface_font(obj) ((lxb_html_font_element_t *) (obj))
#define lxb_html_interface_style(obj) ((lxb_html_style_element_t *) (obj))
#define lxb_css_selector_sp_up_i(num) (num | (1 << 28))
#define lxb_css_syntax_token_string(token) ((lxb_css_syntax_token_string_t *) (token))
#define lxb_html_interface_table(obj) ((lxb_html_table_element_t *) (obj))
#define lxb_css_parser_token_status_wo_ws_m(parser,token) do { if ((token = lxb_css_syntax_parser_token(parser)) == NULL) { return parser->tkz->status; } if (token->type == LXB_CSS_SYNTAX_TOKEN_WHITESPACE) { lxb_css_syntax_parser_consume(parser); if ((token = lxb_css_syntax_parser_token(parser)) == NULL) { return parser->tkz->status; } } } while (false)
#define lxb_css_syntax_token_delim(token) ((lxb_css_syntax_token_delim_t *) (token))
#define lxb_css_syntax_token_ls_bracket(token) ((lxb_css_syntax_token_ls_bracket_t *) (token))
#define lxb_html_interface_track(obj) ((lxb_html_track_element_t *) (obj))
#define lxb_html_tokenizer_state_token_done_wo_check_m(tkz,v_end) do { _lxb_html_tokenizer_state_token_done_m(tkz, v_end) lxb_html_token_clean(tkz->token); } while (0)
#define lxb_html_interface_source(obj) ((lxb_html_source_element_t *) (obj))
#define lexbor_str_get(str,attr) str->attr
#define lxb_html_interface_embed(obj) ((lxb_html_embed_element_t *) (obj))
#define lxb_html_interface_param(obj) ((lxb_html_param_element_t *) (obj))
#define lxb_html_tokenizer_state_token_set_end_down(tkz,v_end,offset) do { tkz->token->end = lexbor_in_node_pos_down(tkz->incoming_node, NULL, v_end, offset); } while (0)
#define lexbor_utils_whitespace(onechar,action,logic) (onechar action ' ' logic onechar action '\t' logic onechar action '\n' logic onechar action '\f' logic onechar action '\r')
#define lxb_html_tokenizer_state_token_attr_set_value_end_oef(tkz) (tkz->token->attr_last->value_end = tkz->last)
#define lxb_css_syntax_token_base(token) ((lxb_css_syntax_token_base_t *) (token))
#define _lxb_html_tokenizer_state_token_done_m(tkz,v_end) tkz->token = tkz->callback_token_done(tkz, tkz->token, tkz->callback_token_ctx); if (tkz->token == NULL) { if (tkz->status == LXB_STATUS_OK) { tkz->status = LXB_STATUS_ERROR; } return v_end; }
#define lxb_css_syntax_token_bad_url(token) ((lxb_css_syntax_token_bad_url_t *) (token))
#define lxb_css_syntax_token_percentage(token) ((lxb_css_syntax_token_percentage_t *) (token))
#define lxb_html_interface_slot(obj) ((lxb_html_slot_element_t *) (obj))
#define lxb_css_syntax_token_function(token) ((lxb_css_syntax_token_function_t *) (token))
#define lxb_html_interface_progress(obj) ((lxb_html_progress_element_t *) (obj))
#define lxb_html_tokenizer_state_set_text(tkz) do { tkz->token->text_start = tkz->start; tkz->token->text_end = tkz->pos; } while (0)
#define lxb_css_parser_string_dup_m(parser,token,_str,mraw) do { if (lxb_css_syntax_token_string_dup(lxb_css_syntax_token_string(token), (_str), (mraw)) != LXB_STATUS_OK) { return lxb_css_parser_fail((parser), LXB_STATUS_ERROR_MEMORY_ALLOCATION); } } while (false)
#define lxb_html_interface_button(obj) ((lxb_html_button_element_t *) (obj))
#define lxb_html_interface_mod(obj) ((lxb_html_mod_element_t *) (obj))
#define lxb_html_interface_template(obj) ((lxb_html_template_element_t *) (obj))
#define lxb_html_interface_br(obj) ((lxb_html_br_element_t *) (obj))
#define lxb_css_syntax_token_lc_bracket(token) ((lxb_css_syntax_token_lc_bracket_t *) (token))
#define lxb_css_syntax_token_colon(token) ((lxb_css_syntax_token_colon_t *) (token))
#define lxb_html_interface_link(obj) ((lxb_html_link_element_t *) (obj))
#define lxb_html_interface_time(obj) ((lxb_html_time_element_t *) (obj))
#define lxb_html_interface_d_list(obj) ((lxb_html_d_list_element_t *) (obj))
#define lxb_css_selector_sp_add_c(sp,num) (lxb_css_selector_sp_set_c((sp), lxb_css_selector_sp_c(sp) + num))
#define lxb_html_interface_body(obj) ((lxb_html_body_element_t *) (obj))
#define lxb_css_syntax_token_delim_char(token) (((lxb_css_syntax_token_delim_t *) (token))->character)
#define lxb_html_interface_directory(obj) ((lxb_html_directory_element_t *) (obj))
#define lxb_html_interface_label(obj) ((lxb_html_label_element_t *) (obj))
#define lxb_dom_interface_text(obj) ((lxb_dom_text_t *) (obj))
#define lxb_html_interface_object(obj) ((lxb_html_object_element_t *) (obj))
#define lxb_html_interface_heading(obj) ((lxb_html_heading_element_t *) (obj))
#define lxb_html_tokenizer_state_append_m(tkz,v_data,size) do { if (lxb_html_tokenizer_temp_append(tkz, (const lxb_char_t *) (v_data), (size))) { return end; } } while (0)
#define lxb_css_syntax_token_hash(token) ((lxb_css_syntax_token_hash_t *) (token))
#define lxb_html_interface_pre(obj) ((lxb_html_pre_element_t *) (obj))
#define lxb_html_tokenizer_state_token_emit_text_not_empty_m(tkz,v_end) do { if (tkz->token->begin != tkz->token->end) { tkz->token->tag_id = LXB_TAG__TEXT; lxb_html_tokenizer_state_set_text(tkz); _lxb_html_tokenizer_state_token_done_m(tkz, v_end) lxb_html_token_clean(tkz->token); } } while (0)
#define lxb_html_interface_meter(obj) ((lxb_html_meter_element_t *) (obj))
#define lxb_html_interface_details(obj) ((lxb_html_details_element_t *) (obj))
#define lxb_html_interface_quote(obj) ((lxb_html_quote_element_t *) (obj))
#define lxb_dom_interface_cdata_section(obj) ((lxb_dom_cdata_section_t *) (obj))
#define lxb_html_interface_anchor(obj) ((lxb_html_anchor_element_t *) (obj))
#define lxb_css_syntax_token_url(token) ((lxb_css_syntax_token_url_t *) (token))
#define lxb_html_tokenizer_state_token_attr_set_value_begin(tkz,v_begin) do { tkz->pos = tkz->start; tkz->token->attr_last->value_begin = v_begin; } while (0)
#define lxb_html_interface_audio(obj) ((lxb_html_audio_element_t *) (obj))
#define lxb_css_syntax_token_cdo(token) ((lxb_css_syntax_token_cdo_t *) (token))
#define lxb_html_tokenizer_state_begin_set(tkz,v_data) (tkz->begin = v_data)
#define lxb_css_syntax_token_rc_bracket(token) ((lxb_css_syntax_token_rc_bracket_t *) (token))
#define lxb_html_interface_dialog(obj) ((lxb_html_dialog_element_t *) (obj))
#define lxb_html_interface_document(obj) ((lxb_html_document_t *) (obj))
#define lxb_css_selector_sp_add_b(sp,num) (lxb_css_selector_sp_set_b((sp), lxb_css_selector_sp_b(sp) + num))
#define lxb_dom_interface_event_target(obj) ((lxb_dom_event_target_t *) (obj))
#define lexbor_mraw_meta_size() (((sizeof(size_t) % LEXBOR_MEM_ALIGN_STEP) != 0) ? sizeof(size_t) + (LEXBOR_MEM_ALIGN_STEP - (sizeof(size_t) % LEXBOR_MEM_ALIGN_STEP)) : sizeof(size_t))
#define lxb_css_parser_token_wo_ws_m(parser,token) do { token = lxb_css_syntax_parser_token(parser); if (token == NULL) { return lxb_css_parser_fail((parser), (parser)->tkz->status); } if (token->type == LXB_CSS_SYNTAX_TOKEN_WHITESPACE) { lxb_css_syntax_parser_consume(parser); token = lxb_css_syntax_parser_token(parser); if (token == NULL) { return lxb_css_parser_fail((parser), (parser)->tkz->status); } } } while (false)
#define lxb_css_syntax_token_ident(token) ((lxb_css_syntax_token_ident_t *) (token))
#define lxb_dom_interface_document_type(obj) ((lxb_dom_document_type_t *) (obj))
#define lexbor_str_set(str,attr) lexbor_str_get(str, attr)
#define lxb_html_interface_data(obj) ((lxb_html_data_element_t *) (obj))
#define lxb_css_selector_sp_add_s(sp,num) (lxb_css_selector_sp_set_s((sp), lxb_css_selector_sp_s(sp) + num))
#define lxb_html_interface_image(obj) ((lxb_html_image_element_t *) (obj))
#define lxb_html_interface_opt_group(obj) ((lxb_html_opt_group_element_t *) (obj))
#define lxb_dom_interface_node(obj) ((lxb_dom_node_t *) (obj))
#define lxb_css_syntax_token_dimension_string(token) (&((lxb_css_syntax_token_dimension_t *) (token))->str)
#define lxb_html_interface_map(obj) ((lxb_html_map_element_t *) (obj))
#define lxb_css_selector_sp_add_a(sp,num) (lxb_css_selector_sp_set_a((sp), lxb_css_selector_sp_a(sp) + num))
#define LEXBOR_SWAR_HAS_ZERO(v) (((v) - LEXBOR_SWAR_ONES) & ~(v) & LEXBOR_SWAR_REPEAT(0x80))
#define lxb_html_interface_base(obj) ((lxb_html_base_element_t *) (obj))
#define lxb_html_interface_head(obj) ((lxb_html_head_element_t *) (obj))
#define lxb_html_interface_li(obj) ((lxb_html_li_element_t *) (obj))
#define lxb_html_interface_output(obj) ((lxb_html_output_element_t *) (obj))
#define lxb_css_syntax_token_comma(token) ((lxb_css_syntax_token_comma_t *) (token))
#define lxb_dom_interface_element(obj) ((lxb_dom_element_t *) (obj))
#define lxb_html_interface_script(obj) ((lxb_html_script_element_t *) (obj))
#define lxb_css_parser_token_next_m(parser,token) do { token = lxb_css_syntax_token_next((parser)->tkz); if (token == NULL) { return lxb_css_parser_fail((parser), (parser)->tkz->status); } } while (false)
#define lxb_css_syntax_token_dimension(token) ((lxb_css_syntax_token_dimension_t *) (token))
#define lexbor_uint64_hl(h,l) (((uint64_t) (h) << 32) + (l))
#define lxb_html_interface_table_col(obj) ((lxb_html_table_col_element_t *) (obj))
#define lxb_css_selector_sp_set_b(sp,num) sp = (LXB_CSS_SELECTOR_SPECIFICITY_MASK_N((sp), 9) | ((num) << 9))
#define lxb_html_interface_meta(obj) ((lxb_html_meta_element_t *) (obj))
#define lxb_html_tokenizer_state_append_replace_m(tkz) do { if (lxb_html_tokenizer_temp_append(tkz, lexbor_str_res_ansi_replacement_character, sizeof(lexbor_str_res_ansi_replacement_character) - 1)) { return end; } } while (0)
#define lxb_css_parser_token_status_m(parser,token) do { if ((token = lxb_css_syntax_parser_token(parser)) == NULL) { return parser->tkz->status; } } while (false)
#define lxb_html_interface_element(obj) ((lxb_html_element_t *) (obj))
#define lxb_html_interface_unknown(obj) ((lxb_html_unknown_element_t *) (obj))
#define lxb_css_syntax_token_cdc(token) ((lxb_css_syntax_token_cdc_t *) (token))
#define lxb_html_interface_title(obj) ((lxb_html_title_element_t *) (obj))
#define lxb_css_syntax_token_unicode_range(token) ((lxb_css_syntax_token_unicode_range_t *) (token))
#define lexbor_min(val1,val2) ((val1) < (val2) ? (val1) : (val2))
#define lxb_html_tokenizer_state_append_data_m(tkz,v_data) do { if (lxb_html_tokenizer_temp_append_data(tkz, v_data)) { return end; } } while (0)
#define lxb_html_interface_canvas(obj) ((lxb_html_canvas_element_t *) (obj))
#define lxb_dom_interface_document(obj) ((lxb_dom_document_t *) (obj))
#define lxb_html_interface_table_section(obj) ((lxb_html_table_section_element_t *) (obj))
#define lxb_html_interface_video(obj) ((lxb_html_video_element_t *) (obj))
#define lxb_css_selector_serialize_write(data,length) do { (status) = cb((lxb_char_t *) (data), (length), (ctx)); if ((status) != LXB_STATUS_OK) { return (status); } } while (false)
#define lxb_html_interface_span(obj) ((lxb_html_span_element_t *) (obj))
#define lxb_dom_interface_document_fragment(obj) ((lxb_dom_document_fragment_t *) (obj))
#define lxb_css_syntax_token_semicolon(token) ((lxb_css_syntax_token_semicolon_t *) (token))
#define lxb_dom_interface_attr(obj) ((lxb_dom_attr_t *) (obj))
#define lxb_html_interface_paragraph(obj) ((lxb_html_paragraph_element_t *) (obj))
#define lxb_dom_interface_shadow_root(obj) ((lxb_dom_shadow_root_t *) (obj))
#define lxb_html_tokenizer_state_set_name_m(tkz) do { lxb_dom_attr_data_t *data; data = lxb_dom_attr_local_name_append(tkz->attrs, tkz->start, tkz->pos - tkz->start); if (data == NULL) { tkz->status = LXB_STATUS_ERROR_MEMORY_ALLOCATION; return end; } tkz->token->attr_last->name = data; } while (0)
#define lxb_html_interface_window(obj) ((lxb_html_window_t *) (obj))
#define lxb_html_interface_o_list(obj) ((lxb_html_o_list_element_t *) (obj))
#define LXB_CSS_SELECTOR_SPECIFICITY_MASK_N(sp,n) ((sp) & ~((((uint32_t) 1 << 9) - 1) << (n)))
#define lxb_html_interface_table_cell(obj) ((lxb_html_table_cell_element_t *) (obj))
#define lxb_html_interface_select(obj) ((lxb_html_select_element_t *) (obj))
#define lxb_css_syntax_token_r_parenthesis(token) ((lxb_css_syntax_token_r_parenthesis_t *) (token))
#define lxb_html_interface_hr(obj) ((lxb_html_hr_element_t *) (obj))
#define lexbor_str_check_size_arg_m(str,size,mraw,plus_len,return_fail) do { void *tmp; if (str->length > (SIZE_MAX - (plus_len))) return (return_fail); if ((str->length + (plus_len)) > (size)) { tmp = lexbor_mraw_realloc(mraw, str->data, (str->length + plus_len)); if (tmp == NULL) { return (return_fail); } str->data = (lxb_char_t *) tmp; } } while (0)
#define lxb_html_interface_frame(obj) ((lxb_html_frame_element_t *) (obj))
#define lxb_dom_interface_character_data(obj) ((lxb_dom_character_data_t *) (obj))
#define lxb_css_selector_sp_set_a(sp,num) sp = (LXB_CSS_SELECTOR_SPECIFICITY_MASK_N((sp), 18) | ((num) << 18))
#define lxb_css_selector_sp_set_c(sp,num) sp = (LXB_CSS_SELECTOR_SPECIFICITY_MASK_N((sp), 0) | (num))
#define lxb_css_selector_sp_set_s(sp,num) sp = (LXB_CSS_SELECTOR_SPECIFICITY_MASK_N((sp), 27) | ((num) << 27))
#define lxb_html_interface_legend(obj) ((lxb_html_legend_element_t *) (obj))
#define lxb_html_interface_media(obj) ((lxb_html_media_element_t *) (obj))
#define lxb_html_tokenizer_state_token_attr_add_m(tkz,attr,v_return) do { attr = lxb_html_token_attr_append(tkz->token, tkz->dobj_token_attr); if (attr == NULL) { tkz->status = LXB_STATUS_ERROR_MEMORY_ALLOCATION; return v_return; } } while (0)
#define lxb_html_tokenizer_state_token_done_m(tkz,v_end) do { if (tkz->token->begin != tkz->token->end) { _lxb_html_tokenizer_state_token_done_m(tkz, v_end) } lxb_html_token_clean(tkz->token); tkz->pos = tkz->start; } while (0)
#define lxb_html_interface_picture(obj) ((lxb_html_picture_element_t *) (obj))
#define lxb_css_syntax_token_at_keyword(token) ((lxb_css_syntax_token_at_keyword_t *) (token))
#define lxb_html_interface_form(obj) ((lxb_html_form_element_t *) (obj))
#define lxb_html_interface_field_set(obj) ((lxb_html_field_set_element_t *) (obj))
#define LEXBOR_SWAR_REPEAT(x) (LEXBOR_SWAR_ONES * (x))
#define lxb_html_tokenizer_state_token_set_end_eof(tkz) (tkz->token->end = tkz->last)
#define lxb_css_syntax_token_l_parenthesis(token) ((lxb_css_syntax_token_l_parenthesis_t *) (token))
#define lxb_html_interface_html(obj) ((lxb_html_html_element_t *) (obj))
#define lxb_html_tokenizer_state_token_attr_set_name_end_oef(tkz) (tkz->token->attr_last->name_end = tkz->last)
#define lxb_html_interface_menu(obj) ((lxb_html_menu_element_t *) (obj))
#define lxb_dom_interface_comment(obj) ((lxb_dom_comment_t *) (obj))
#define lexbor_bst_root(bst) (bst)->root
#define lxb_html_interface_text_area(obj) ((lxb_html_text_area_element_t *) (obj))
#define lxb_html_interface_input(obj) ((lxb_html_input_element_t *) (obj))
#define lxb_html_interface_option(obj) ((lxb_html_option_element_t *) (obj))
#define lxb_html_tokenizer_state_set_value_m(tkz) do { lxb_html_token_attr_t *attr = tkz->token->attr_last; attr->value_size = (size_t) (tkz->pos - tkz->start); attr->value = lexbor_mraw_alloc(tkz->attrs_mraw, attr->value_size + 1); if (attr->value == NULL) { tkz->status = LXB_STATUS_ERROR_MEMORY_ALLOCATION; return end; } memcpy(attr->value, tkz->start, attr->value_size); attr->value[attr->value_size] = 0x00; } while (0)
#define lexbor_bst_root_ref(bst) &((bst)->root)
#define lxb_html_interface_iframe(obj) ((lxb_html_iframe_element_t *) (obj))
#define lxb_css_syntax_token_bad_string(token) ((lxb_css_syntax_token_bad_string_t *) (token))
#define lxb_css_syntax_token_whitespace(token) ((lxb_css_syntax_token_whitespace_t *) (token))
#define lxb_html_tokenizer_state_token_attr_set_name_begin(tkz,v_begin) do { tkz->pos = tkz->start; tkz->token->attr_last->name_begin = v_begin; } while (0)
#define lxb_css_parser_token_m(parser,token) do { token = lxb_css_syntax_parser_token(parser); if (token == NULL) { return lxb_css_parser_fail((parser), (parser)->tkz->status); } } while (false)
#define lxb_css_selector_sp_a(sp) (((sp) >> 18) & ~LXB_CSS_SELECTOR_SPECIFICITY_MASK)
#define lxb_css_selector_sp_b(sp) (((sp) >> 9) & ~LXB_CSS_SELECTOR_SPECIFICITY_MASK)
#define lxb_css_selector_sp_c(sp) ((sp) & ~LXB_CSS_SELECTOR_SPECIFICITY_MASK)
#define lxb_css_selector_sp_i(sp) ((sp) >> 28)
#define lxb_html_tokenizer_state_token_set_end(tkz,v_end) (tkz->token->end = v_end)
#define lxb_css_selector_sp_s(sp) (((sp) >> 27) & ~((((uint32_t) 1 << 31) - 1) << (1)))
#define lxb_css_selector_sp_set_i(sp,num) sp = (LXB_CSS_SELECTOR_SPECIFICITY_MASK_N((sp), 28) | ((num) << 28))
#define lxb_html_tokenizer_state_token_attr_set_value_end(tkz,v_end) (tkz->token->attr_last->value_end = v_end)
#define lexbor_serialize_write(cb,data,length,ctx,status) do { (status) = (cb)((lxb_char_t *) (data), (length), (ctx)); if ((status) != LXB_STATUS_OK) { return (status); } } while (false)
#define lxb_html_interface_u_list(obj) ((lxb_html_u_list_element_t *) (obj))
#define lxb_html_tokenizer_state_set_tag_m(tkz,_start,_end) do { const lxb_tag_data_t *tag; tag = lxb_tag_append_lower(tkz->tags, (_start), (_end) - (_start)); if (tag == NULL) { tkz->status = LXB_STATUS_ERROR_MEMORY_ALLOCATION; return end; } tkz->token->tag_id = tag->tag_id; } while (0)
#define lxb_css_selector_sp_up_s(num) (num | (1 << 27))
#define lxb_html_interface_data_list(obj) ((lxb_html_data_list_element_t *) (obj))
#define lexbor_diyfp(_s,_e) (lexbor_diyfp_t) { .significand = (_s), .exp = (int) (_e) }
#define lxb_css_syntax_token_number(token) ((lxb_css_syntax_token_number_t *) (token))
#define lxb_html_tokenizer_state_token_attr_set_name_end(tkz,v_end) (tkz->token->attr_last->name_end = v_end)
#define lxb_html_interface_marquee(obj) ((lxb_html_marquee_element_t *) (obj))
#define lxb_html_interface_table_row(obj) ((lxb_html_table_row_element_t *) (obj))
#define lexbor_assert(val) 
#define lxb_html_interface_table_caption(obj) ((lxb_html_table_caption_element_t *) (obj))
#define lxb_css_syntax_token_rs_bracket(token) ((lxb_css_syntax_token_rs_bracket_t *) (token))
#define lxb_html_tokenizer_state_token_set_begin(tkz,v_begin) do { tkz->pos = tkz->start; tkz->token->begin = v_begin; } while (0)
#define lxb_html_interface_area(obj) ((lxb_html_area_element_t *) (obj))
#define lxb_css_parser_token_status_next_m(parser,token) do { token = lxb_css_syntax_token_next((parser)->tkz); if (token == NULL) { return parser->tkz->status; } } while (false)
#define LXB_API
#define LXB_EXTERN extern
#define lxb_inline
#define LXB_DEPRECATED(func) func
