module parserino.lexbor.css.at_rule.const_;

import core.stdc.stdint;
// D port of lexbor (https://github.com/lexbor/lexbor), Apache-2.0.
// Original author: Alexander Borisov <borisov@lexbor.com>

public import parserino.lexbor.css.value.const_;

extern(C) @nogc nothrow:
__gshared:

// ---- const.h ----
/*
 * Copyright (C) 2026 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/names.py"!
 * Do not change this file!
 */

enum {
    LXB_CSS_AT_RULE__UNDEF = 0x0000,
    LXB_CSS_AT_RULE__CUSTOM = 0x0001,
    LXB_CSS_AT_RULE_FONT_FACE = 0x0002,
    LXB_CSS_AT_RULE_MEDIA = 0x0003,
    LXB_CSS_AT_RULE_NAMESPACE = 0x0004,
    LXB_CSS_AT_RULE__LAST_ENTRY = 0x0005
}
alias lxb_css_at_rule_type_t = uintptr_t;
