/++
 Names of tags, attributes and namespaces.

 Known names have a fixed id (`Tag`, `AttrName`); other names get an id when a
 document meets them (see `NameTable`). Generated by tools/gen/gen_names.py.

 The lists are derived from lexbor (https://github.com/lexbor/lexbor).
 Copyright (C) 2018-2026 Alexander Borisov (lexbor), Apache-2.0: see LICENSE-lexbor and NOTICE-lexbor.
+/
module parserino.names;

import parserino.arena;

@nogc nothrow pure @safe:

/// Namespaces. `None` is no namespace (as for most attributes); nothing uses `Any`.
enum Ns : ubyte
{
    None, Any, Html, Math, Svg, Xlink, Xml, Xmlns,
}

/++ Known tags. Unknown tag names get ids from `Tag.Last` on.
 + The members are the names in PascalCase (`annotation-xml` is `AnnotationXml`); `Undef`
 + (no tag), `EndOfFile` and the `...Node` members name the nodes that are not elements.
 +/
enum Tag : uint
{
    Undef = 0,
    EndOfFile = 1,
    TextNode = 2,
    DocumentNode = 3,
    CommentNode = 4,
    DoctypeNode = 5,
    ProcessingInstructionNode = 6,
    A = 7,
    Abbr = 8,
    Acronym = 9,
    Address = 10,
    Altglyph = 11,
    Altglyphdef = 12,
    Altglyphitem = 13,
    Animatecolor = 14,
    Animatemotion = 15,
    Animatetransform = 16,
    AnnotationXml = 17,
    Applet = 18,
    Area = 19,
    Article = 20,
    Aside = 21,
    Audio = 22,
    B = 23,
    Base = 24,
    Basefont = 25,
    Bdi = 26,
    Bdo = 27,
    Bgsound = 28,
    Big = 29,
    Blink = 30,
    Blockquote = 31,
    Body = 32,
    Br = 33,
    Button = 34,
    Canvas = 35,
    Caption = 36,
    Center = 37,
    Cite = 38,
    Clippath = 39,
    Code = 40,
    Col = 41,
    Colgroup = 42,
    Data = 43,
    Datalist = 44,
    Dd = 45,
    Del = 46,
    Desc = 47,
    Details = 48,
    Dfn = 49,
    Dialog = 50,
    Dir = 51,
    Div = 52,
    Dl = 53,
    Dt = 54,
    Em = 55,
    Embed = 56,
    Feblend = 57,
    Fecolormatrix = 58,
    Fecomponenttransfer = 59,
    Fecomposite = 60,
    Feconvolvematrix = 61,
    Fediffuselighting = 62,
    Fedisplacementmap = 63,
    Fedistantlight = 64,
    Fedropshadow = 65,
    Feflood = 66,
    Fefunca = 67,
    Fefuncb = 68,
    Fefuncg = 69,
    Fefuncr = 70,
    Fegaussianblur = 71,
    Feimage = 72,
    Femerge = 73,
    Femergenode = 74,
    Femorphology = 75,
    Feoffset = 76,
    Fepointlight = 77,
    Fespecularlighting = 78,
    Fespotlight = 79,
    Fetile = 80,
    Feturbulence = 81,
    Fieldset = 82,
    Figcaption = 83,
    Figure = 84,
    Font = 85,
    Footer = 86,
    Foreignobject = 87,
    Form = 88,
    Frame = 89,
    Frameset = 90,
    Glyphref = 91,
    H1 = 92,
    H2 = 93,
    H3 = 94,
    H4 = 95,
    H5 = 96,
    H6 = 97,
    Head = 98,
    Header = 99,
    Hgroup = 100,
    Hr = 101,
    Html = 102,
    I = 103,
    Iframe = 104,
    Image = 105,
    Img = 106,
    Input = 107,
    Ins = 108,
    Isindex = 109,
    Kbd = 110,
    Keygen = 111,
    Label = 112,
    Legend = 113,
    Li = 114,
    Lineargradient = 115,
    Link = 116,
    Listing = 117,
    Main = 118,
    Malignmark = 119,
    Map = 120,
    Mark = 121,
    Marquee = 122,
    Math = 123,
    Menu = 124,
    Meta = 125,
    Meter = 126,
    Mfenced = 127,
    Mglyph = 128,
    Mi = 129,
    Mn = 130,
    Mo = 131,
    Ms = 132,
    Mtext = 133,
    Multicol = 134,
    Nav = 135,
    Nextid = 136,
    Nobr = 137,
    Noembed = 138,
    Noframes = 139,
    Noscript = 140,
    Object = 141,
    Ol = 142,
    Optgroup = 143,
    Option = 144,
    Output = 145,
    P = 146,
    Param = 147,
    Path = 148,
    Picture = 149,
    Plaintext = 150,
    Pre = 151,
    Progress = 152,
    Q = 153,
    Radialgradient = 154,
    Rb = 155,
    Rp = 156,
    Rt = 157,
    Rtc = 158,
    Ruby = 159,
    S = 160,
    Samp = 161,
    Script = 162,
    Search = 163,
    Section = 164,
    Select = 165,
    Selectedcontent = 166,
    Slot = 167,
    Small = 168,
    Source = 169,
    Spacer = 170,
    Span = 171,
    Strike = 172,
    Strong = 173,
    Style = 174,
    Sub = 175,
    Summary = 176,
    Sup = 177,
    Svg = 178,
    Table = 179,
    Tbody = 180,
    Td = 181,
    Template = 182,
    Textarea = 183,
    Textpath = 184,
    Tfoot = 185,
    Th = 186,
    Thead = 187,
    Time = 188,
    Title = 189,
    Tr = 190,
    Track = 191,
    Tt = 192,
    U = 193,
    Ul = 194,
    Var = 195,
    Video = 196,
    Wbr = 197,
    Xmp = 198,
    Last = 199,
}

/// Names of the known tags (lowercase)
immutable string[Tag.Last] tagNames = [
    "#undef",
    "#end-of-file",
    "#text",
    "#document",
    "!--",
    "!doctype",
    "?ProcessingInstruction",
    "a",
    "abbr",
    "acronym",
    "address",
    "altglyph",
    "altglyphdef",
    "altglyphitem",
    "animatecolor",
    "animatemotion",
    "animatetransform",
    "annotation-xml",
    "applet",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "basefont",
    "bdi",
    "bdo",
    "bgsound",
    "big",
    "blink",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "center",
    "cite",
    "clippath",
    "code",
    "col",
    "colgroup",
    "data",
    "datalist",
    "dd",
    "del",
    "desc",
    "details",
    "dfn",
    "dialog",
    "dir",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "feblend",
    "fecolormatrix",
    "fecomponenttransfer",
    "fecomposite",
    "feconvolvematrix",
    "fediffuselighting",
    "fedisplacementmap",
    "fedistantlight",
    "fedropshadow",
    "feflood",
    "fefunca",
    "fefuncb",
    "fefuncg",
    "fefuncr",
    "fegaussianblur",
    "feimage",
    "femerge",
    "femergenode",
    "femorphology",
    "feoffset",
    "fepointlight",
    "fespecularlighting",
    "fespotlight",
    "fetile",
    "feturbulence",
    "fieldset",
    "figcaption",
    "figure",
    "font",
    "footer",
    "foreignobject",
    "form",
    "frame",
    "frameset",
    "glyphref",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "image",
    "img",
    "input",
    "ins",
    "isindex",
    "kbd",
    "keygen",
    "label",
    "legend",
    "li",
    "lineargradient",
    "link",
    "listing",
    "main",
    "malignmark",
    "map",
    "mark",
    "marquee",
    "math",
    "menu",
    "meta",
    "meter",
    "mfenced",
    "mglyph",
    "mi",
    "mn",
    "mo",
    "ms",
    "mtext",
    "multicol",
    "nav",
    "nextid",
    "nobr",
    "noembed",
    "noframes",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "param",
    "path",
    "picture",
    "plaintext",
    "pre",
    "progress",
    "q",
    "radialgradient",
    "rb",
    "rp",
    "rt",
    "rtc",
    "ruby",
    "s",
    "samp",
    "script",
    "search",
    "section",
    "select",
    "selectedcontent",
    "slot",
    "small",
    "source",
    "spacer",
    "span",
    "strike",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "svg",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "textpath",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "tt",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
    "xmp",
];

/// Categories of the tags in the tree construction ("special", "formatting", scopes, ...)
enum Category : ubyte
{
    Ordinary = 0x01,
    Special = 0x02,
    Formatting = 0x04,
    Scope = 0x08,
    ScopeListItem = 0x10,
    ScopeButton = 0x20,
    ScopeTable = 0x40,
}

/// Categories of each tag, for each namespace
immutable ubyte[Ns.max + 1][Tag.Last] tagCategories = [
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 58, 0, 0, 0, 0],
    [0, 0, 58, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 34, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 58, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 58, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 58, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 122, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 58, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 58, 0, 0, 0, 0],
    [0, 0, 0, 58, 0, 0, 0, 0],
    [0, 0, 0, 58, 0, 0, 0, 0],
    [0, 0, 0, 58, 0, 0, 0, 0],
    [0, 0, 0, 58, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 58, 0, 0, 0, 0, 0],
    [0, 0, 18, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 58, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 122, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 58, 0, 0, 0, 0, 0],
    [0, 0, 122, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 58, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 58, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0, 0],
    [0, 0, 18, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0],
];

/++ Known attributes. Unknown names get ids from `AttrName.Last` on.
 + The members are the names in PascalCase (`accept-charset` is `AcceptCharset`); `Undef` is no attribute.
 +/
enum AttrName : uint
{
    Undef = 0,
    Accept = 1,
    AcceptCharset = 2,
    Active = 3,
    Align = 4,
    Alink = 5,
    Alt = 6,
    Axis = 7,
    Bgcolor = 8,
    Charset = 9,
    Checked = 10,
    Class = 11,
    Clear = 12,
    Codetype = 13,
    Color = 14,
    Compact = 15,
    Content = 16,
    Declare = 17,
    Defer = 18,
    Dir = 19,
    Direction = 20,
    Disabled = 21,
    Enctype = 22,
    Face = 23,
    Focus = 24,
    For = 25,
    Frame = 26,
    Height = 27,
    Hover = 28,
    Href = 29,
    Hreflang = 30,
    Html = 31,
    HttpEquiv = 32,
    Id = 33,
    Is = 34,
    Lang = 35,
    Language = 36,
    Link = 37,
    Maxlength = 38,
    Media = 39,
    Method = 40,
    Multiple = 41,
    Nohref = 42,
    Noresize = 43,
    Noshade = 44,
    Nowrap = 45,
    Placeholder = 46,
    Pool = 47,
    Public = 48,
    Readonly = 49,
    Rel = 50,
    Required = 51,
    Rev = 52,
    Rules = 53,
    Scheme = 54,
    Scope = 55,
    Scrolling = 56,
    Selected = 57,
    Shape = 58,
    Size = 59,
    Slot = 60,
    Src = 61,
    Style = 62,
    System = 63,
    Target = 64,
    Text = 65,
    Title = 66,
    Type = 67,
    Valign = 68,
    Valuetype = 69,
    Vlink = 70,
    Width = 71,
    Xmlns = 72,
    Last = 73,
}

/// Names of the known attributes
immutable string[AttrName.Last] attrNames = [
    "#undef",
    "accept",
    "accept-charset",
    "active",
    "align",
    "alink",
    "alt",
    "axis",
    "bgcolor",
    "charset",
    "checked",
    "class",
    "clear",
    "codetype",
    "color",
    "compact",
    "content",
    "declare",
    "defer",
    "dir",
    "direction",
    "disabled",
    "enctype",
    "face",
    "focus",
    "for",
    "frame",
    "height",
    "hover",
    "href",
    "hreflang",
    "html",
    "http-equiv",
    "id",
    "is",
    "lang",
    "language",
    "link",
    "maxlength",
    "media",
    "method",
    "multiple",
    "nohref",
    "noresize",
    "noshade",
    "nowrap",
    "placeholder",
    "pool",
    "public",
    "readonly",
    "rel",
    "required",
    "rev",
    "rules",
    "scheme",
    "scope",
    "scrolling",
    "selected",
    "shape",
    "size",
    "slot",
    "src",
    "style",
    "system",
    "target",
    "text",
    "title",
    "type",
    "valign",
    "valuetype",
    "vlink",
    "width",
    "xmlns",
];

/// Id of a known tag (`name` must be lowercase), or `Tag.Undef`
Tag knownTag(scope const(char)[] name) @trusted { return cast(Tag) staticLookup!tagNames(name); }

/// Id of a known attribute (`name` must be lowercase), or `AttrName.Undef`
AttrName knownAttr(scope const(char)[] name) @trusted { return cast(AttrName) staticLookup!attrNames(name); }

///
unittest
{
    assert(knownTag("div") == Tag.Div);
    assert(knownTag("template") == Tag.Template);
    assert(knownTag("nope") == Tag.Undef);
    assert(knownAttr("href") == AttrName.Href);
    static assert(knownTag("svg") == Tag.Svg);
}

/++ Interned names of a document: known names have their static id, the others
 + get new ids (from `first` on) the first time they are seen.
 +/
struct NameTable
{
@nogc nothrow pure @safe:
    @disable this(this);

    /// Id of `name`, adding it if needed. It returns 0 if out of memory.
    uint intern(scope const(char)[] name, ref Arena arena, uint first)
    {
        if (auto id = find(name, first)) return id;

        // A null name marks the empty slots: the empty name is a non-null ""
        const(char)[] copy = name.length ? arena.dup(name) : "";
        if (copy is null) return 0;

        if ((count + 1) * 2 > slots.length && !grow()) return 0;

        names.put(copy);
        if (names.failed) return 0;
        insert(Entry(copy, first + cast(uint) count), hash(name));
        count++;
        return first + cast(uint) count - 1;
    }

    /// Id of `name` if already interned, else 0
    uint find(scope const(char)[] name, uint first) const
    {
        if (slots.length == 0) return 0;

        auto mask = slots.length - 1;
        for (auto i = hash(name) & mask; slots[i].name !is null; i = (i + 1) & mask)
            if (slots[i].name == name) return slots[i].id;

        return 0;
    }

    /// Name of an id (from `first` on)
    const(char)[] name(uint id, uint first) const { return names[id - first]; }

    ~this() @trusted
    {
        import core.memory : pureFree;
        if (!__ctfe && slots.ptr !is null) pureFree(slots.ptr);
    }

    private:

    static struct Entry { const(char)[] name; uint id; }

    Entry[] slots;
    Buffer!(const(char)[]) names;
    size_t count;

    void insert(Entry e, size_t h)
    {
        auto mask = slots.length - 1;
        auto i = h & mask;
        while (slots[i].name !is null) i = (i + 1) & mask;
        slots[i] = e;
    }

    bool grow() @trusted
    {
        import core.memory : pureCalloc, pureFree;

        auto n = slots.length == 0 ? 64 : slots.length * 2;
        Entry[] ns;
        if (__ctfe) ns = new Entry[n];
        else
        {
            auto p = cast(Entry*) pureCalloc(n, Entry.sizeof);
            if (p is null) return false;
            ns = p[0 .. n];
        }

        auto old = slots;
        slots = ns;
        foreach (ref e; old) if (e.name !is null) insert(e, hash(e.name));
        if (!__ctfe && old.ptr !is null) pureFree(old.ptr);
        return true;
    }
}

/// FNV-1a
size_t hash(scope const(char)[] s)
{
    uint h = 2166136261;
    foreach (c; s) { h ^= c; h *= 16777619; }
    return h;
}

private:

// A static hash table (built at compile time) from a list of names to their index
template staticLookup(alias names)
{
    enum size_t size = () {
        size_t n = 1;
        while (n < names.length * 4) n *= 2;
        return n;
    }();

    static immutable ushort[size] table = () {
        ushort[size] t;
        foreach (i, n; names)
        {
            if (i == 0) continue;
            auto j = hash(n) & (size - 1);
            while (t[j] != 0) j = (j + 1) & (size - 1);
            t[j] = cast(ushort) i;
        }
        return t;
    }();

    uint staticLookup(scope const(char)[] name)
    {
        for (auto j = hash(name) & (size - 1); table[j] != 0; j = (j + 1) & (size - 1))
            if (names[table[j]] == name) return table[j];
        return 0;
    }
}
