module parserino.lexbor.html.tree.open_elements_res;

import parserino.lexbor.html.interfaces.option_element;
import parserino.lexbor.html.interfaces.document;
import parserino.lexbor.tag.const_;
// D port of lexbor (https://github.com/lexbor/lexbor), Apache-2.0.
// Original author: Alexander Borisov <borisov@lexbor.com>


extern(C) @nogc nothrow:
__gshared:

// ---- open_elements_res.h ----
/*
 * Copyright (C) 2018-2026 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */
const(lxb_html_document_open_elements_pop_f)[LXB_TAG__LAST_ENTRY] lxb_html_tree_open_elements_pop_res = [
    /* LXB_TAG__UNDEF */
    null,
    /* LXB_TAG__END_OF_FILE */
    null,
    /* LXB_TAG__TEXT */
    null,
    /* LXB_TAG__DOCUMENT */
    null,
    /* LXB_TAG__EM_COMMENT */
    null,
    /* LXB_TAG__EM_DOCTYPE */
    null,
    /* LXB_TAG__PROCESSINGINSTRUCTION */
    null,
    /* LXB_TAG_A */
    null,
    /* LXB_TAG_ABBR */
    null,
    /* LXB_TAG_ACRONYM */
    null,
    /* LXB_TAG_ADDRESS */
    null,
    /* LXB_TAG_ALTGLYPH */
    null,
    /* LXB_TAG_ALTGLYPHDEF */
    null,
    /* LXB_TAG_ALTGLYPHITEM */
    null,
    /* LXB_TAG_ANIMATECOLOR */
    null,
    /* LXB_TAG_ANIMATEMOTION */
    null,
    /* LXB_TAG_ANIMATETRANSFORM */
    null,
    /* LXB_TAG_ANNOTATION_XML */
    null,
    /* LXB_TAG_APPLET */
    null,
    /* LXB_TAG_AREA */
    null,
    /* LXB_TAG_ARTICLE */
    null,
    /* LXB_TAG_ASIDE */
    null,
    /* LXB_TAG_AUDIO */
    null,
    /* LXB_TAG_B */
    null,
    /* LXB_TAG_BASE */
    null,
    /* LXB_TAG_BASEFONT */
    null,
    /* LXB_TAG_BDI */
    null,
    /* LXB_TAG_BDO */
    null,
    /* LXB_TAG_BGSOUND */
    null,
    /* LXB_TAG_BIG */
    null,
    /* LXB_TAG_BLINK */
    null,
    /* LXB_TAG_BLOCKQUOTE */
    null,
    /* LXB_TAG_BODY */
    null,
    /* LXB_TAG_BR */
    null,
    /* LXB_TAG_BUTTON */
    null,
    /* LXB_TAG_CANVAS */
    null,
    /* LXB_TAG_CAPTION */
    null,
    /* LXB_TAG_CENTER */
    null,
    /* LXB_TAG_CITE */
    null,
    /* LXB_TAG_CLIPPATH */
    null,
    /* LXB_TAG_CODE */
    null,
    /* LXB_TAG_COL */
    null,
    /* LXB_TAG_COLGROUP */
    null,
    /* LXB_TAG_DATA */
    null,
    /* LXB_TAG_DATALIST */
    null,
    /* LXB_TAG_DD */
    null,
    /* LXB_TAG_DEL */
    null,
    /* LXB_TAG_DESC */
    null,
    /* LXB_TAG_DETAILS */
    null,
    /* LXB_TAG_DFN */
    null,
    /* LXB_TAG_DIALOG */
    null,
    /* LXB_TAG_DIR */
    null,
    /* LXB_TAG_DIV */
    null,
    /* LXB_TAG_DL */
    null,
    /* LXB_TAG_DT */
    null,
    /* LXB_TAG_EM */
    null,
    /* LXB_TAG_EMBED */
    null,
    /* LXB_TAG_FEBLEND */
    null,
    /* LXB_TAG_FECOLORMATRIX */
    null,
    /* LXB_TAG_FECOMPONENTTRANSFER */
    null,
    /* LXB_TAG_FECOMPOSITE */
    null,
    /* LXB_TAG_FECONVOLVEMATRIX */
    null,
    /* LXB_TAG_FEDIFFUSELIGHTING */
    null,
    /* LXB_TAG_FEDISPLACEMENTMAP */
    null,
    /* LXB_TAG_FEDISTANTLIGHT */
    null,
    /* LXB_TAG_FEDROPSHADOW */
    null,
    /* LXB_TAG_FEFLOOD */
    null,
    /* LXB_TAG_FEFUNCA */
    null,
    /* LXB_TAG_FEFUNCB */
    null,
    /* LXB_TAG_FEFUNCG */
    null,
    /* LXB_TAG_FEFUNCR */
    null,
    /* LXB_TAG_FEGAUSSIANBLUR */
    null,
    /* LXB_TAG_FEIMAGE */
    null,
    /* LXB_TAG_FEMERGE */
    null,
    /* LXB_TAG_FEMERGENODE */
    null,
    /* LXB_TAG_FEMORPHOLOGY */
    null,
    /* LXB_TAG_FEOFFSET */
    null,
    /* LXB_TAG_FEPOINTLIGHT */
    null,
    /* LXB_TAG_FESPECULARLIGHTING */
    null,
    /* LXB_TAG_FESPOTLIGHT */
    null,
    /* LXB_TAG_FETILE */
    null,
    /* LXB_TAG_FETURBULENCE */
    null,
    /* LXB_TAG_FIELDSET */
    null,
    /* LXB_TAG_FIGCAPTION */
    null,
    /* LXB_TAG_FIGURE */
    null,
    /* LXB_TAG_FONT */
    null,
    /* LXB_TAG_FOOTER */
    null,
    /* LXB_TAG_FOREIGNOBJECT */
    null,
    /* LXB_TAG_FORM */
    null,
    /* LXB_TAG_FRAME */
    null,
    /* LXB_TAG_FRAMESET */
    null,
    /* LXB_TAG_GLYPHREF */
    null,
    /* LXB_TAG_H1 */
    null,
    /* LXB_TAG_H2 */
    null,
    /* LXB_TAG_H3 */
    null,
    /* LXB_TAG_H4 */
    null,
    /* LXB_TAG_H5 */
    null,
    /* LXB_TAG_H6 */
    null,
    /* LXB_TAG_HEAD */
    null,
    /* LXB_TAG_HEADER */
    null,
    /* LXB_TAG_HGROUP */
    null,
    /* LXB_TAG_HR */
    null,
    /* LXB_TAG_HTML */
    null,
    /* LXB_TAG_I */
    null,
    /* LXB_TAG_IFRAME */
    null,
    /* LXB_TAG_IMAGE */
    null,
    /* LXB_TAG_IMG */
    null,
    /* LXB_TAG_INPUT */
    null,
    /* LXB_TAG_INS */
    null,
    /* LXB_TAG_ISINDEX */
    null,
    /* LXB_TAG_KBD */
    null,
    /* LXB_TAG_KEYGEN */
    null,
    /* LXB_TAG_LABEL */
    null,
    /* LXB_TAG_LEGEND */
    null,
    /* LXB_TAG_LI */
    null,
    /* LXB_TAG_LINEARGRADIENT */
    null,
    /* LXB_TAG_LINK */
    null,
    /* LXB_TAG_LISTING */
    null,
    /* LXB_TAG_MAIN */
    null,
    /* LXB_TAG_MALIGNMARK */
    null,
    /* LXB_TAG_MAP */
    null,
    /* LXB_TAG_MARK */
    null,
    /* LXB_TAG_MARQUEE */
    null,
    /* LXB_TAG_MATH */
    null,
    /* LXB_TAG_MENU */
    null,
    /* LXB_TAG_META */
    null,
    /* LXB_TAG_METER */
    null,
    /* LXB_TAG_MFENCED */
    null,
    /* LXB_TAG_MGLYPH */
    null,
    /* LXB_TAG_MI */
    null,
    /* LXB_TAG_MN */
    null,
    /* LXB_TAG_MO */
    null,
    /* LXB_TAG_MS */
    null,
    /* LXB_TAG_MTEXT */
    null,
    /* LXB_TAG_MULTICOL */
    null,
    /* LXB_TAG_NAV */
    null,
    /* LXB_TAG_NEXTID */
    null,
    /* LXB_TAG_NOBR */
    null,
    /* LXB_TAG_NOEMBED */
    null,
    /* LXB_TAG_NOFRAMES */
    null,
    /* LXB_TAG_NOSCRIPT */
    null,
    /* LXB_TAG_OBJECT */
    null,
    /* LXB_TAG_OL */
    null,
    /* LXB_TAG_OPTGROUP */
    null,
    /* LXB_TAG_OPTION */
    &lxb_html_option_element_pop_open_elements,
    /* LXB_TAG_OUTPUT */
    null,
    /* LXB_TAG_P */
    null,
    /* LXB_TAG_PARAM */
    null,
    /* LXB_TAG_PATH */
    null,
    /* LXB_TAG_PICTURE */
    null,
    /* LXB_TAG_PLAINTEXT */
    null,
    /* LXB_TAG_PRE */
    null,
    /* LXB_TAG_PROGRESS */
    null,
    /* LXB_TAG_Q */
    null,
    /* LXB_TAG_RADIALGRADIENT */
    null,
    /* LXB_TAG_RB */
    null,
    /* LXB_TAG_RP */
    null,
    /* LXB_TAG_RT */
    null,
    /* LXB_TAG_RTC */
    null,
    /* LXB_TAG_RUBY */
    null,
    /* LXB_TAG_S */
    null,
    /* LXB_TAG_SAMP */
    null,
    /* LXB_TAG_SCRIPT */
    null,
    /* LXB_TAG_SEARCH */
    null,
    /* LXB_TAG_SECTION */
    null,
    /* LXB_TAG_SELECT */
    null,
    /* LXB_TAG_SELECTEDCONTENT */
    null,
    /* LXB_TAG_SLOT */
    null,
    /* LXB_TAG_SMALL */
    null,
    /* LXB_TAG_SOURCE */
    null,
    /* LXB_TAG_SPACER */
    null,
    /* LXB_TAG_SPAN */
    null,
    /* LXB_TAG_STRIKE */
    null,
    /* LXB_TAG_STRONG */
    null,
    /* LXB_TAG_STYLE */
    null,
    /* LXB_TAG_SUB */
    null,
    /* LXB_TAG_SUMMARY */
    null,
    /* LXB_TAG_SUP */
    null,
    /* LXB_TAG_SVG */
    null,
    /* LXB_TAG_TABLE */
    null,
    /* LXB_TAG_TBODY */
    null,
    /* LXB_TAG_TD */
    null,
    /* LXB_TAG_TEMPLATE */
    null,
    /* LXB_TAG_TEXTAREA */
    null,
    /* LXB_TAG_TEXTPATH */
    null,
    /* LXB_TAG_TFOOT */
    null,
    /* LXB_TAG_TH */
    null,
    /* LXB_TAG_THEAD */
    null,
    /* LXB_TAG_TIME */
    null,
    /* LXB_TAG_TITLE */
    null,
    /* LXB_TAG_TR */
    null,
    /* LXB_TAG_TRACK */
    null,
    /* LXB_TAG_TT */
    null,
    /* LXB_TAG_U */
    null,
    /* LXB_TAG_UL */
    null,
    /* LXB_TAG_VAR */
    null,
    /* LXB_TAG_VIDEO */
    null,
    /* LXB_TAG_WBR */
    null,
    /* LXB_TAG_XMP */
    null
];
