#!/bin/bash

# Cross-compiling lexbor for Windows x64
cmake . -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_CROSSCOMPILING=true -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DLEXBOR_BUILD_TESTS=OFF -DLEXBOR_BUILD_EXAMPLES=OFF -DLEXBOR_BUILD_SEPARATELY=OFF -DLEXBOR_BUILD_STATIC=OFF -DLEXBOR_BUILD_SHARED=ON
make -j8
