module parserino.lexbor.html.attribute_steps_res;

import parserino.lexbor.html.interfaces.option_element;
import parserino.lexbor.dom.interfaces.document;
import parserino.lexbor.tag.const_;
// D port of lexbor (https://github.com/lexbor/lexbor), Apache-2.0.
// Original author: Alexander Borisov <borisov@lexbor.com>


extern(C) @nogc nothrow:
__gshared:

// ---- attribute_steps_res.h ----
/*
 * Copyright (C) 2018-2026 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */
const(lxb_dom_document_attr_mutation_cb_t)[LXB_TAG__LAST_ENTRY] lxb_html_attribute_steps_res_default = [
    /* LXB_TAG__UNDEF */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG__END_OF_FILE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG__TEXT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG__DOCUMENT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG__EM_COMMENT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG__EM_DOCTYPE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG__PROCESSINGINSTRUCTION */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_A */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ABBR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ACRONYM */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ADDRESS */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ALTGLYPH */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ALTGLYPHDEF */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ALTGLYPHITEM */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ANIMATECOLOR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ANIMATEMOTION */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ANIMATETRANSFORM */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ANNOTATION_XML */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_APPLET */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_AREA */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ARTICLE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ASIDE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_AUDIO */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_B */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BASE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BASEFONT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BDI */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BDO */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BGSOUND */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BIG */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BLINK */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BLOCKQUOTE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BODY */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_BUTTON */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_CANVAS */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_CAPTION */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_CENTER */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_CITE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_CLIPPATH */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_CODE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_COL */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_COLGROUP */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DATA */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DATALIST */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DD */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DEL */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DESC */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DETAILS */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DFN */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DIALOG */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DIR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DIV */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DL */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_DT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_EM */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_EMBED */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEBLEND */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FECOLORMATRIX */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FECOMPONENTTRANSFER */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FECOMPOSITE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FECONVOLVEMATRIX */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEDIFFUSELIGHTING */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEDISPLACEMENTMAP */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEDISTANTLIGHT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEDROPSHADOW */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEFLOOD */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEFUNCA */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEFUNCB */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEFUNCG */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEFUNCR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEGAUSSIANBLUR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEIMAGE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEMERGE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEMERGENODE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEMORPHOLOGY */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEOFFSET */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FEPOINTLIGHT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FESPECULARLIGHTING */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FESPOTLIGHT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FETILE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FETURBULENCE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FIELDSET */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FIGCAPTION */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FIGURE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FONT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FOOTER */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FOREIGNOBJECT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FORM */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FRAME */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_FRAMESET */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_GLYPHREF */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_H1 */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_H2 */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_H3 */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_H4 */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_H5 */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_H6 */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_HEAD */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_HEADER */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_HGROUP */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_HR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_HTML */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_I */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_IFRAME */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_IMAGE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_IMG */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_INPUT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_INS */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_ISINDEX */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_KBD */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_KEYGEN */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_LABEL */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_LEGEND */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_LI */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_LINEARGRADIENT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_LINK */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_LISTING */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MAIN */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MALIGNMARK */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MAP */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MARK */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MARQUEE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MATH */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MENU */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_META */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_METER */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MFENCED */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MGLYPH */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MI */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MN */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MO */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MS */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MTEXT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_MULTICOL */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_NAV */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_NEXTID */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_NOBR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_NOEMBED */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_NOFRAMES */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_NOSCRIPT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_OBJECT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_OL */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_OPTGROUP */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_OPTION */
    {change: &lxb_html_option_attr_steps_change, append: &lxb_html_option_attr_steps_change, remove: &lxb_html_option_attr_steps_remove, replace: null},
    /* LXB_TAG_OUTPUT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_P */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_PARAM */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_PATH */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_PICTURE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_PLAINTEXT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_PRE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_PROGRESS */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_Q */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_RADIALGRADIENT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_RB */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_RP */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_RT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_RTC */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_RUBY */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_S */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SAMP */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SCRIPT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SEARCH */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SECTION */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SELECT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SELECTEDCONTENT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SLOT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SMALL */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SOURCE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SPACER */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SPAN */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_STRIKE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_STRONG */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_STYLE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SUB */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SUMMARY */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SUP */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_SVG */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TABLE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TBODY */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TD */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TEMPLATE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TEXTAREA */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TEXTPATH */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TFOOT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TH */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_THEAD */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TIME */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TITLE */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TRACK */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_TT */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_U */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_UL */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_VAR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_VIDEO */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_WBR */
    {change: null, append: null, remove: null, replace: null},
    /* LXB_TAG_XMP */
    {change: null, append: null, remove: null, replace: null}
];
