module parserino.lexbor.dom.interfaces.attr_res;

import parserino.lexbor.dom.interfaces.attr;
// D port of lexbor (https://github.com/lexbor/lexbor), Apache-2.0.
// Original author: Alexander Borisov <borisov@lexbor.com>

public import parserino.lexbor.core.shs;
public import parserino.lexbor.dom.interfaces.attr_const;

extern(C) @nogc nothrow:
__gshared:

// ---- attr_res.h ----
/*
 * Copyright (C) 2019-2020 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/dom/attr.py"!
 * Do not change this file!
 */

const(lxb_dom_attr_data_t)[LXB_DOM_ATTR__LAST_ENTRY] lxb_dom_attr_res_data_default = [
    {{u: {short_str: lexbor_hash_short_str("#undef")}, length: 6, next: null},
     LXB_DOM_ATTR__UNDEF, 1, true},
    {{u: {short_str: lexbor_hash_short_str("active")}, length: 6, next: null},
     LXB_DOM_ATTR_ACTIVE, 1, true},
    {{u: {short_str: lexbor_hash_short_str("alt")}, length: 3, next: null},
     LXB_DOM_ATTR_ALT, 1, true},
    {{u: {short_str: lexbor_hash_short_str("charset")}, length: 7, next: null},
     LXB_DOM_ATTR_CHARSET, 1, true},
    {{u: {short_str: lexbor_hash_short_str("checked")}, length: 7, next: null},
     LXB_DOM_ATTR_CHECKED, 1, true},
    {{u: {short_str: lexbor_hash_short_str("class")}, length: 5, next: null},
     LXB_DOM_ATTR_CLASS, 1, true},
    {{u: {short_str: lexbor_hash_short_str("color")}, length: 5, next: null},
     LXB_DOM_ATTR_COLOR, 1, true},
    {{u: {short_str: lexbor_hash_short_str("content")}, length: 7, next: null},
     LXB_DOM_ATTR_CONTENT, 1, true},
    {{u: {short_str: lexbor_hash_short_str("dir")}, length: 3, next: null},
     LXB_DOM_ATTR_DIR, 1, true},
    {{u: {short_str: lexbor_hash_short_str("disabled")}, length: 8, next: null},
     LXB_DOM_ATTR_DISABLED, 1, true},
    {{u: {short_str: lexbor_hash_short_str("face")}, length: 4, next: null},
     LXB_DOM_ATTR_FACE, 1, true},
    {{u: {short_str: lexbor_hash_short_str("focus")}, length: 5, next: null},
     LXB_DOM_ATTR_FOCUS, 1, true},
    {{u: {short_str: lexbor_hash_short_str("for")}, length: 3, next: null},
     LXB_DOM_ATTR_FOR, 1, true},
    {{u: {short_str: lexbor_hash_short_str("height")}, length: 6, next: null},
     LXB_DOM_ATTR_HEIGHT, 1, true},
    {{u: {short_str: lexbor_hash_short_str("hover")}, length: 5, next: null},
     LXB_DOM_ATTR_HOVER, 1, true},
    {{u: {short_str: lexbor_hash_short_str("href")}, length: 4, next: null},
     LXB_DOM_ATTR_HREF, 1, true},
    {{u: {short_str: lexbor_hash_short_str("html")}, length: 4, next: null},
     LXB_DOM_ATTR_HTML, 1, true},
    {{u: {short_str: lexbor_hash_short_str("http-equiv")}, length: 10, next: null},
     LXB_DOM_ATTR_HTTP_EQUIV, 1, true},
    {{u: {short_str: lexbor_hash_short_str("id")}, length: 2, next: null},
     LXB_DOM_ATTR_ID, 1, true},
    {{u: {short_str: lexbor_hash_short_str("is")}, length: 2, next: null},
     LXB_DOM_ATTR_IS, 1, true},
    {{u: {short_str: lexbor_hash_short_str("maxlength")}, length: 9, next: null},
     LXB_DOM_ATTR_MAXLENGTH, 1, true},
    {{u: {short_str: lexbor_hash_short_str("placeholder")}, length: 11, next: null},
     LXB_DOM_ATTR_PLACEHOLDER, 1, true},
    {{u: {short_str: lexbor_hash_short_str("pool")}, length: 4, next: null},
     LXB_DOM_ATTR_POOL, 1, true},
    {{u: {short_str: lexbor_hash_short_str("public")}, length: 6, next: null},
     LXB_DOM_ATTR_PUBLIC, 1, true},
    {{u: {short_str: lexbor_hash_short_str("readonly")}, length: 8, next: null},
     LXB_DOM_ATTR_READONLY, 1, true},
    {{u: {short_str: lexbor_hash_short_str("required")}, length: 8, next: null},
     LXB_DOM_ATTR_REQUIRED, 1, true},
    {{u: {short_str: lexbor_hash_short_str("scheme")}, length: 6, next: null},
     LXB_DOM_ATTR_SCHEME, 1, true},
    {{u: {short_str: lexbor_hash_short_str("selected")}, length: 8, next: null},
     LXB_DOM_ATTR_SELECTED, 1, true},
    {{u: {short_str: lexbor_hash_short_str("size")}, length: 4, next: null},
     LXB_DOM_ATTR_SIZE, 1, true},
    {{u: {short_str: lexbor_hash_short_str("slot")}, length: 4, next: null},
     LXB_DOM_ATTR_SLOT, 1, true},
    {{u: {short_str: lexbor_hash_short_str("src")}, length: 3, next: null},
     LXB_DOM_ATTR_SRC, 1, true},
    {{u: {short_str: lexbor_hash_short_str("style")}, length: 5, next: null},
     LXB_DOM_ATTR_STYLE, 1, true},
    {{u: {short_str: lexbor_hash_short_str("system")}, length: 6, next: null},
     LXB_DOM_ATTR_SYSTEM, 1, true},
    {{u: {short_str: lexbor_hash_short_str("title")}, length: 5, next: null},
     LXB_DOM_ATTR_TITLE, 1, true},
    {{u: {short_str: lexbor_hash_short_str("type")}, length: 4, next: null},
     LXB_DOM_ATTR_TYPE, 1, true},
    {{u: {short_str: lexbor_hash_short_str("width")}, length: 5, next: null},
     LXB_DOM_ATTR_WIDTH, 1, true}
];

const(lexbor_shs_entry_t)[40] lxb_dom_attr_res_shs_data = [
    {null, null, 39, 0},
    {"slot", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_SLOT], 4, 2},
    {"#undef", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR__UNDEF], 6, 0},
    {"active", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_ACTIVE], 6, 0},
    {"html", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_HTML], 4, 0},
    {"href", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_HREF], 4, 4},
    {"hover", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_HOVER], 5, 7},
    {"readonly", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_READONLY], 8, 0},
    {"disabled", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_DISABLED], 8, 0},
    {"color", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_COLOR], 5, 0},
    {"src", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_SRC], 3, 8},
    {"required", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_REQUIRED], 8, 0},
    {"id", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_ID], 2, 11},
    {"system", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_SYSTEM], 6, 0},
    {"pool", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_POOL], 4, 13},
    {"placeholder", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_PLACEHOLDER], 11, 0},
    {"selected", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_SELECTED], 8, 0},
    {"scheme", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_SCHEME], 6, 0},
    {"http-equiv", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_HTTP_EQUIV], 10, 0},
    {"size", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_SIZE], 4, 16},
    {"style", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_STYLE], 5, 0},
    {"class", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_CLASS], 5, 17},
    {"width", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_WIDTH], 5, 0},
    {"height", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_HEIGHT], 6, 0},
    {"focus", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_FOCUS], 5, 18},
    {"public", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_PUBLIC], 6, 0},
    {"content", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_CONTENT], 7, 0},
    {"is", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_IS], 2, 0},
    {"type", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_TYPE], 4, 0},
    {"title", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_TITLE], 5, 0},
    {null, null, 0, 0},
    {"for", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_FOR], 3, 0},
    {"face", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_FACE], 4, 22},
    {"alt", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_ALT], 3, 23},
    {"dir", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_DIR], 3, 0},
    {"charset", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_CHARSET], 7, 26},
    {"maxlength", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_MAXLENGTH], 9, 0},
    {null, null, 0, 0},
    {"checked", cast(void*) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_CHECKED], 7, 0},
    {null, null, 0, 0}
];
