module parserino.lexbor.ns.const_;

import core.stdc.stdint;
// D port of lexbor (https://github.com/lexbor/lexbor), Apache-2.0.
// Original author: Alexander Borisov <borisov@lexbor.com>


extern(C) @nogc nothrow:
__gshared:

// ---- const.h ----
/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */

enum LXB_NS_CONST_VERSION = "253D4AFDA959234B48A478B956C3C777";

alias lxb_ns_id_t = uintptr_t;
alias lxb_ns_prefix_id_t = uintptr_t;

enum lxb_ns_id_enum_t {
    LXB_NS__UNDEF = 0x00,
    LXB_NS__ANY = 0x01,
    LXB_NS_HTML = 0x02,
    LXB_NS_MATH = 0x03,
    LXB_NS_SVG = 0x04,
    LXB_NS_XLINK = 0x05,
    LXB_NS_XML = 0x06,
    LXB_NS_XMLNS = 0x07,
    LXB_NS__LAST_ENTRY = 0x08
}
alias LXB_NS__UNDEF = lxb_ns_id_enum_t.LXB_NS__UNDEF;
alias LXB_NS__ANY = lxb_ns_id_enum_t.LXB_NS__ANY;
alias LXB_NS_HTML = lxb_ns_id_enum_t.LXB_NS_HTML;
alias LXB_NS_MATH = lxb_ns_id_enum_t.LXB_NS_MATH;
alias LXB_NS_SVG = lxb_ns_id_enum_t.LXB_NS_SVG;
alias LXB_NS_XLINK = lxb_ns_id_enum_t.LXB_NS_XLINK;
alias LXB_NS_XML = lxb_ns_id_enum_t.LXB_NS_XML;
alias LXB_NS_XMLNS = lxb_ns_id_enum_t.LXB_NS_XMLNS;
alias LXB_NS__LAST_ENTRY = lxb_ns_id_enum_t.LXB_NS__LAST_ENTRY;

