module parserino.lexbor.ns.res;

import parserino.lexbor.ns.ns;
import parserino.lexbor.core.shs;
import parserino.lexbor.ns.const_;
// D port of lexbor (https://github.com/lexbor/lexbor), Apache-2.0.
// Original author: Alexander Borisov <borisov@lexbor.com>


extern(C) @nogc nothrow:
__gshared:

// ---- res.h ----
/*
 * Copyright (C) 2018-2019 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */
const(lxb_ns_data_t)[LXB_NS__LAST_ENTRY] lxb_ns_res_data = [
    {{u: {short_str: lexbor_hash_short_str("")}, length: 0, next: null}, LXB_NS__UNDEF, 1, true},
    {{u: {short_str: lexbor_hash_short_str("")}, length: 0, next: null}, LXB_NS__ANY, 1, true},
    {{u: {long_str: cast(lxb_char_t*) "http://www.w3.org/1999/xhtml"}, length: 28, next: null}, LXB_NS_HTML, 1, true},
    {{u: {long_str: cast(lxb_char_t*) "http://www.w3.org/1998/Math/MathML"}, length: 34, next: null}, LXB_NS_MATH, 1, true},
    {{u: {long_str: cast(lxb_char_t*) "http://www.w3.org/2000/svg"}, length: 26, next: null}, LXB_NS_SVG, 1, true},
    {{u: {long_str: cast(lxb_char_t*) "http://www.w3.org/1999/xlink"}, length: 28, next: null}, LXB_NS_XLINK, 1, true},
    {{u: {long_str: cast(lxb_char_t*) "http://www.w3.org/XML/1998/namespace"}, length: 36, next: null}, LXB_NS_XML, 1, true},
    {{u: {long_str: cast(lxb_char_t*) "http://www.w3.org/2000/xmlns/"}, length: 29, next: null}, LXB_NS_XMLNS, 1, true}
];

const(lxb_ns_prefix_data_t)[LXB_NS__LAST_ENTRY] lxb_ns_prefix_res_data = [
    {{u: {short_str: lexbor_hash_short_str("#undef")}, length: 6, next: null}, LXB_NS__UNDEF, 1, true},
    {{u: {short_str: lexbor_hash_short_str("#any")}, length: 4, next: null}, LXB_NS__ANY, 1, true},
    {{u: {short_str: lexbor_hash_short_str("html")}, length: 4, next: null}, LXB_NS_HTML, 1, true},
    {{u: {short_str: lexbor_hash_short_str("math")}, length: 4, next: null}, LXB_NS_MATH, 1, true},
    {{u: {short_str: lexbor_hash_short_str("svg")}, length: 3, next: null}, LXB_NS_SVG, 1, true},
    {{u: {short_str: lexbor_hash_short_str("xlink")}, length: 5, next: null}, LXB_NS_XLINK, 1, true},
    {{u: {short_str: lexbor_hash_short_str("xml")}, length: 3, next: null}, LXB_NS_XML, 1, true},
    {{u: {short_str: lexbor_hash_short_str("xmlns")}, length: 5, next: null}, LXB_NS_XMLNS, 1, true}
];

const(lexbor_shs_entry_t)[29] lxb_ns_res_shs_data = [
    {null, null, 28, 0}, {"html", cast(void*) &lxb_ns_prefix_res_data[2], 4, 0},
    {"xmlns", cast(void*) &lxb_ns_prefix_res_data[7], 5, 0}, {null, null, 0, 0},
    {null, null, 0, 0}, {null, null, 0, 0},
    {null, null, 0, 0}, {"svg", cast(void*) &lxb_ns_prefix_res_data[4], 3, 0},
    {null, null, 0, 0}, {null, null, 0, 0},
    {null, null, 0, 0}, {null, null, 0, 0},
    {null, null, 0, 0}, {null, null, 0, 0},
    {null, null, 0, 0}, {null, null, 0, 0},
    {null, null, 0, 0}, {"math", cast(void*) &lxb_ns_prefix_res_data[3], 4, 0},
    {null, null, 0, 0}, {null, null, 0, 0},
    {null, null, 0, 0}, {"#undef", cast(void*) &lxb_ns_prefix_res_data[0], 6, 0},
    {"xlink", cast(void*) &lxb_ns_prefix_res_data[5], 5, 0}, {null, null, 0, 0},
    {null, null, 0, 0}, {null, null, 0, 0},
    {"#any", cast(void*) &lxb_ns_prefix_res_data[1], 4, 0}, {null, null, 0, 0},
    {"xml", cast(void*) &lxb_ns_prefix_res_data[6], 3, 0}
];

const(lexbor_shs_entry_t)[23] lxb_ns_res_shs_link_data = [
    {null, null, 22, 0},
    {"http://www.w3.org/1999/xhtml", cast(void*) &lxb_ns_res_data[2], 28, 0},
    {null, null, 0, 0},
    {null, null, 0, 0},
    {null, null, 0, 0},
    {null, null, 0, 0},
    {"http://www.w3.org/2000/xmlns/", cast(void*) &lxb_ns_res_data[7], 29, 0},
    {"http://www.w3.org/1998/math/mathml", cast(void*) &lxb_ns_res_data[3], 34, 0},
    {null, null, 0, 0},
    {"http://www.w3.org/1999/xlink", cast(void*) &lxb_ns_res_data[5], 28, 0},
    {null, null, 0, 0},
    {null, null, 0, 0},
    {null, null, 0, 0},
    {null, null, 0, 0},
    {null, null, 0, 0},
    {null, null, 0, 0},
    {"#any", cast(void*) &lxb_ns_res_data[1], 4, 0},
    {"http://www.w3.org/2000/svg", cast(void*) &lxb_ns_res_data[4], 26, 0},
    {null, null, 0, 0},
    {"#undef", cast(void*) &lxb_ns_res_data[0], 6, 0},
    {null, null, 0, 0},
    {"http://www.w3.org/xml/1998/namespace", cast(void*) &lxb_ns_res_data[6], 36, 0},
    {null, null, 0, 0}
];
